add_newline = true
command_timeout = 500
follow_symlinks = true
format = "[](fg:#ca9ee6)$os$username$hostname$localip$container[](bg:#babbf1 fg:#ca9ee6)$directory[](fg:#babbf1 bg:#c6d0f5)$git_branch$git_status[](fg:#c6d0f5 bg:#eebebe)$python$bun$c$cmake$dart$golang$haskell$java$kotlin$kubernetes$lua$nodejs$php$rust$swift$zig[](fg:#eebebe bg:#f2d5cf)$docker_context$nix_shell[](fg:#f2d5cf)$fill[](fg:#ca9ee6)$time[](fg:#ca9ee6)$line_break$character"
scan_timeout = 30

[aws]
disabled = true
format = "on [$symbol$profile(\\($region\\))]($style)"
symbol = " "

[azure]
disabled = true
format = "on [$symbol$subscription]($style)"
symbol = " "

[bun]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[c]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[character]
error_symbol = "[~>](bold #e78284)"
success_symbol = "[](bold #a6d189)"
vimcmd_replace_one_symbol = "[](bold #ca9ee6)"
vimcmd_replace_symbol = "[](bold #ca9ee6)"
vimcmd_symbol = "[](bold #a6d189)"
vimcmd_visual_symbol = "[](bold #e5c890)"

[cmake]
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[cmd_duration]
min_time = 2000

[conda]
symbol = " "

[container]
disabled = false
format = "[ $symbol $name ]($style)"
style = "bg:#ca9ee6 fg:#303446"
symbol = " "

[custom.yazi]
description = "Indicate when the shell was launched by `yazi`"
style = "bg:#ca9ee6 fg:#303446"
symbol = " "
when = "test -n \"$YAZI_LEVEL\""

[dart]
disabled = true
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[directory]
format = "[ $path ]($style)"
home_symbol = "~"
read_only = " "
style = "fg:#303446 bg:#babbf1"
truncate_to_repo = true
truncation_length = 10
truncation_symbol = "…/"

[directory.substitutions]
Code = "󰲋 "
Desktop = " "
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "
Videos = " "

[docker_context]
disabled = false
format = "[ $symbol( $context) ]($style)"
style = "fg:#303446 bg:#f2d5cf"
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[fill]
style = "bg:none fg:none"
symbol = " "

[gcloud]
disabled = true
format = "on [$symbol$active(/$project)(\\($region\\))]($style)"
symbol = "󱇶 "

[git_branch]
disabled = false
format = "[[ $symbol $branch ](fg:#303446 bg:#c6d0f5)]($style)"
style = "bg:#c6d0f5"
symbol = ""

[git_status]
disabled = false
format = "[[($all_status$ahead_behind )](fg:#303446 bg:#c6d0f5)]($style)"
style = "bg:#c6d0f5"

[golang]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[haskell]
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[hg_branch]
symbol = " "

[hostname]
disabled = false
format = "[$ssh_symbol]($style)"
ssh_only = true
ssh_symbol = " "
style = "bg:#ca9ee6 fg:#303446"

[java]
disabled = true
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[julia]
symbol = " "

[kotlin]
disabled = true
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[kubernetes]
disabled = false
format = "[[ $symbol$context( $namespace ) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = "󱃾 "

[line_break]
disabled = false

[localip]
disabled = false
format = "[ $localipv4 ]($style)"
ssh_only = true
style = "bg:#ca9ee6 fg:#303446"

[lua]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = "󰆥 "

[nix_shell]
disabled = true
format = "[[$symbol$state( ($name))](fg:#303446 bg:#f2d5cf)]($style)"
heuristic = false
impure_msg = ""
pure_msg = ""
style = "bg:#f2d5cf"
symbol = " "

[nodejs]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[os]
disabled = false
format = "[$symbol]($style)"
style = "bg:#ca9ee6 fg:#303446"

[os.symbols]
AlmaLinux = " "
Alpine = " "
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = " "
Debian = "󰣚 "
Fedora = "󰣛 "
FreeBSD = " "
Gentoo = "󰣨 "
Kali = " "
Linux = "󰌽 "
Macos = "󰀵"
Manjaro = " "
Mint = "󰣭 "
NixOS = " "
Pop = " "
Raspbian = " "
RedHatEnterprise = "󱄛 "
Redhat = " "
RockyLinux = " "
SUSE = " "
Ubuntu = "󰕈 "
Unknown = ""
Void = " "
Windows = "󰍲 "

[package]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = "󰏗 "
version_format = "v$raw"

[perl]
symbol = " "

[php]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[python]
detect_folders = [".venv"]
disabled = false
format = "[[ $symbol( $version )(($virtualenv) )](fg:#303446 bg:#eebebe)]($style)"
pyenv_version_name = false
python_binary = ["python", "python3"]
style = "bg:#eebebe"
symbol = " "
version_format = "$raw"

[rlang]
symbol = " "

[ruby]
symbol = " "

[rust]
disabled = false
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[scala]
symbol = ""

[shlvl]
disabled = false
format = "[$shlvl]($style) "
repeat = true
style = "bg:#c6d0f5"
symbol = " "
threshold = 2

[swift]
disabled = true
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "

[terraform]
symbol = "󱁢 "

[time]
disabled = false
format = "[  $time]($style)"
style = "bg:#ca9ee6 fg:#303446"
use_12hr = false

[username]
detect_env_vars = ["SSH_CONNECTION", "SSH_CLIENT", "SSH_TTY"]
disabled = false
format = "[ $user ]($style)"
show_always = true
style_root = "bg:#ca9ee6 fg:#303446"
style_user = "bg:#ca9ee6 fg:#303446"

[zig]
disabled = true
format = "[[ $symbol( $version) ](fg:#303446 bg:#eebebe)]($style)"
style = "bg:#eebebe"
symbol = " "
