[[manager.prepend_keymap]]
desc = "Enter the child directory, or open the file"
on = ["l"]
run = "plugin smart-enter"

[[manager.prepend_keymap]]
desc = "Paste into the hovered directory or CWD"
on = ["p"]
run = "plugin smart-paste"

[[manager.prepend_keymap]]
desc = "Copy the selected files to the system clipboard while yanking"
on = ["y"]
run = ["shell 'for path in \"$@\"; do echo \"file://$path\"; done | wl-copy -t text/uri-list' --confirm\n", "yank"]

[[manager.prepend_keymap]]
desc = "Maximize or restore preview pane"
on = ["T"]
run = "plugin max-preview"

[[manager.prepend_keymap]]
desc = "Move the cursor up"
on = ["k"]
run = "plugin arrow --args=-1"

[[manager.prepend_keymap]]
desc = "Move the cursor down"
on = ["j"]
run = "plugin arrow --args=1"

[[manager.prepend_keymap]]
desc = "Go to the root of the current Git repository"
on = ["g", "r"]
run = "shell 'ya emit cd \"$(git rev-parse --show-toplevel)\"' --confirm\n"

[[manager.prepend_keymap]]
desc = "run lazygit"
on = ["g", "i"]
run = "plugin lazygit"

[[manager.prepend_keymap]]
desc = "Toggle tree/list dir preview"
on = ["E"]
run = "plugin eza-preview"

[[manager.prepend_keymap]]
desc = "Chmod the selected files"
on = ["c,m"]
run = "plugin chmod"

[[manager.prepend_keymap]]
desc = "Compress with ouch"
on = ["C"]
run = "plugin ouch --args=zip"
