[[completion.keymap]]
desc = "Cancel completion"
on = "<C-c>"
run = "close"

[[completion.keymap]]
desc = "Submit the completion"
on = "<Tab>"
run = "close --submit"

[[completion.keymap]]
desc = "Submit the completion and input"
on = "<Enter>"
run = ["close --submit", "close_input --submit"]

[[completion.keymap]]
desc = "Move cursor up"
on = "<A-k>"
run = "arrow -1"

[[completion.keymap]]
desc = "Move cursor down"
on = "<A-j>"
run = "arrow 1"

[[completion.keymap]]
desc = "Move cursor up"
on = "<Up>"
run = "arrow -1"

[[completion.keymap]]
desc = "Move cursor down"
on = "<Down>"
run = "arrow 1"

[[completion.keymap]]
desc = "Move cursor up"
on = "<C-p>"
run = "arrow -1"

[[completion.keymap]]
desc = "Move cursor down"
on = "<C-n>"
run = "arrow 1"

[[completion.keymap]]
desc = "Open help"
on = "~"
run = "help"

[[completion.keymap]]
desc = "Open help"
on = "<F1>"
run = "help"

[[confirm.keymap]]
desc = "Cancel the confirm"
on = "<Esc>"
run = "close"

[[confirm.keymap]]
desc = "Cancel the confirm"
on = "<C-[>"
run = "close"

[[confirm.keymap]]
desc = "Cancel the confirm"
on = "<C-c>"
run = "close"

[[confirm.keymap]]
desc = "Submit the confirm"
on = "<Enter>"
run = "close --submit"

[[confirm.keymap]]
desc = "Cancel the confirm"
on = "n"
run = "close"

[[confirm.keymap]]
desc = "Submit the confirm"
on = "y"
run = "close --submit"

[[confirm.keymap]]
desc = "Move cursor up"
on = "k"
run = "arrow -1"

[[confirm.keymap]]
desc = "Move cursor down"
on = "j"
run = "arrow 1"

[[confirm.keymap]]
desc = "Move cursor up"
on = "<Up>"
run = "arrow -1"

[[confirm.keymap]]
desc = "Move cursor down"
on = "<Down>"
run = "arrow 1"

[[confirm.keymap]]
desc = "Open help"
on = "~"
run = "help"

[[confirm.keymap]]
desc = "Open help"
on = "<F1>"
run = "help"

[[help.keymap]]
desc = "Clear the filter, or hide the help"
on = "<Esc>"
run = "escape"

[[help.keymap]]
desc = "Clear the filter, or hide the help"
on = "<C-[>"
run = "escape"

[[help.keymap]]
desc = "Exit the process"
on = "q"
run = "close"

[[help.keymap]]
desc = "Hide the help"
on = "<C-c>"
run = "close"

[[help.keymap]]
desc = "Move cursor up"
on = "k"
run = "arrow -1"

[[help.keymap]]
desc = "Move cursor down"
on = "j"
run = "arrow 1"

[[help.keymap]]
desc = "Move cursor up"
on = "<Up>"
run = "arrow -1"

[[help.keymap]]
desc = "Move cursor down"
on = "<Down>"
run = "arrow 1"

[[help.keymap]]
desc = "Apply a filter for the help items"
on = "f"
run = "filter"

[[input.keymap]]
desc = "Cancel input"
on = "<C-c>"
run = "close"

[[input.keymap]]
desc = "Submit input"
on = "<Enter>"
run = "close --submit"

[[input.keymap]]
desc = "Go back the normal mode, or cancel input"
on = "<Esc>"
run = "escape"

[[input.keymap]]
desc = "Go back the normal mode, or cancel input"
on = "<C-[>"
run = "escape"

[[input.keymap]]
desc = "Enter insert mode"
on = "i"
run = "insert"

[[input.keymap]]
desc = "Enter append mode"
on = "a"
run = "insert --append"

[[input.keymap]]
desc = "Move to the BOL, and enter insert mode"
on = "I"
run = ["move -999", "insert"]

[[input.keymap]]
desc = "Move to the EOL, and enter append mode"
on = "A"
run = ["move 999", "insert --append"]

[[input.keymap]]
desc = "Enter visual mode"
on = "v"
run = "visual"

[[input.keymap]]
desc = "Enter visual mode and select all"
on = "V"
run = ["move -999", "visual", "move 999"]

[[input.keymap]]
desc = "Move back a character"
on = "h"
run = "move -1"

[[input.keymap]]
desc = "Move forward a character"
on = "l"
run = "move 1"

[[input.keymap]]
desc = "Move back a character"
on = "<Left>"
run = "move -1"

[[input.keymap]]
desc = "Move forward a character"
on = "<Right>"
run = "move 1"

[[input.keymap]]
desc = "Move back a character"
on = "<C-b>"
run = "move -1"

[[input.keymap]]
desc = "Move forward a character"
on = "<C-f>"
run = "move 1"

[[input.keymap]]
desc = "Move back to the start of the current or previous word"
on = "b"
run = "backward"

[[input.keymap]]
desc = "Move forward to the start of the next word"
on = "w"
run = "forward"

[[input.keymap]]
desc = "Move forward to the end of the current or next word"
on = "e"
run = "forward --end-of-word"

[[input.keymap]]
desc = "Move back to the start of the current or previous word"
on = "<A-b>"
run = "backward"

[[input.keymap]]
desc = "Move forward to the end of the current or next word"
on = "<A-f>"
run = "forward --end-of-word"

[[input.keymap]]
desc = "Move to the BOL"
on = "0"
run = "move -999"

[[input.keymap]]
desc = "Move to the EOL"
on = "$"
run = "move 999"

[[input.keymap]]
desc = "Move to the BOL"
on = "<C-a>"
run = "move -999"

[[input.keymap]]
desc = "Move to the EOL"
on = "<C-e>"
run = "move 999"

[[input.keymap]]
desc = "Move to the BOL"
on = "<Home>"
run = "move -999"

[[input.keymap]]
desc = "Move to the EOL"
on = "<End>"
run = "move 999"

[[input.keymap]]
desc = "Delete the character before the cursor"
on = "<Backspace>"
run = "backspace"

[[input.keymap]]
desc = "Delete the character under the cursor"
on = "<Delete>"
run = "backspace --under"

[[input.keymap]]
desc = "Delete the character before the cursor"
on = "<C-h>"
run = "backspace"

[[input.keymap]]
desc = "Delete the character under the cursor"
on = "<C-d>"
run = "backspace --under"

[[input.keymap]]
desc = "Kill backwards to the BOL"
on = "<C-u>"
run = "kill bol"

[[input.keymap]]
desc = "Kill forwards to the EOL"
on = "<C-k>"
run = "kill eol"

[[input.keymap]]
desc = "Kill backwards to the start of the current word"
on = "<C-w>"
run = "kill backward"

[[input.keymap]]
desc = "Kill forwards to the end of the current word"
on = "<A-d>"
run = "kill forward"

[[input.keymap]]
desc = "Cut the selected characters"
on = "d"
run = "delete --cut"

[[input.keymap]]
desc = "Cut until the EOL"
on = "D"
run = ["delete --cut", "move 999"]

[[input.keymap]]
desc = "Cut the selected characters, and enter insert mode"
on = "c"
run = "delete --cut --insert"

[[input.keymap]]
desc = "Cut until the EOL, and enter insert mode"
on = "C"
run = ["delete --cut --insert", "move 999"]

[[input.keymap]]
desc = "Cut the current character"
on = "x"
run = ["delete --cut", "move 1 --in-operating"]

[[input.keymap]]
desc = "Copy the selected characters"
on = "y"
run = "yank"

[[input.keymap]]
desc = "Paste the copied characters after the cursor"
on = "p"
run = "paste"

[[input.keymap]]
desc = "Paste the copied characters before the cursor"
on = "P"
run = "paste --before"

[[input.keymap]]
desc = "Undo the last operation"
on = "u"
run = "undo"

[[input.keymap]]
desc = "Redo the last operation"
on = "<C-r>"
run = "redo"

[[input.keymap]]
desc = "Open help"
on = "~"
run = "help"

[[input.keymap]]
desc = "Open help"
on = "<F1>"
run = "help"

[[input.prepend_keymap]]
desc = "Cancel input"
on = ["<Esc>"]
run = "close"

[[manager.keymap]]
desc = "Exit visual mode, clear selected, or cancel search"
on = "<Esc>"
run = "escape"

[[manager.keymap]]
desc = "Exit visual mode, clear selected, or cancel search"
on = "<C-[>"
run = "escape"

[[manager.keymap]]
desc = "Exit the process"
on = "q"
run = "quit"

[[manager.keymap]]
desc = "Exit the process without writing cwd-file"
on = "Q"
run = "quit --no-cwd-file"

[[manager.keymap]]
desc = "Close the current tab, or quit if it is last tab"
on = "<C-c>"
run = "close"

[[manager.keymap]]
desc = "Suspend the process"
on = "<C-z>"
run = "suspend"

[[manager.keymap]]
desc = "Move cursor up"
on = "k"
run = "arrow -1"

[[manager.keymap]]
desc = "Move cursor down"
on = "j"
run = "arrow 1"

[[manager.keymap]]
desc = "Move cursor up"
on = "<Up>"
run = "arrow -1"

[[manager.keymap]]
desc = "Move cursor down"
on = "<Down>"
run = "arrow 1"

[[manager.keymap]]
desc = "Move cursor up half page"
on = "<C-u>"
run = "arrow -50%"

[[manager.keymap]]
desc = "Move cursor down half page"
on = "<C-d>"
run = "arrow 50%"

[[manager.keymap]]
desc = "Move cursor up one page"
on = "<C-b>"
run = "arrow -100%"

[[manager.keymap]]
desc = "Move cursor down one page"
on = "<C-f>"
run = "arrow 100%"

[[manager.keymap]]
desc = "Move cursor up half page"
on = "<S-PageUp>"
run = "arrow -50%"

[[manager.keymap]]
desc = "Move cursor down half page"
on = "<S-PageDown>"
run = "arrow 50%"

[[manager.keymap]]
desc = "Move cursor up one page"
on = "<PageUp>"
run = "arrow -100%"

[[manager.keymap]]
desc = "Move cursor down one page"
on = "<PageDown>"
run = "arrow 100%"

[[manager.keymap]]
desc = "Move cursor to the top"
on = ["g", "g"]
run = "arrow top"

[[manager.keymap]]
desc = "Move cursor to the bottom"
on = "G"
run = "arrow bottom"

[[manager.keymap]]
desc = "Go back to the parent directory"
on = "h"
run = "leave"

[[manager.keymap]]
desc = "Enter the child directory"
on = "l"
run = "enter"

[[manager.keymap]]
desc = "Go back to the parent directory"
on = "<Left>"
run = "leave"

[[manager.keymap]]
desc = "Enter the child directory"
on = "<Right>"
run = "enter"

[[manager.keymap]]
desc = "Go back to the previous directory"
on = "H"
run = "back"

[[manager.keymap]]
desc = "Go forward to the next directory"
on = "L"
run = "forward"

[[manager.keymap]]
desc = "Seek up 5 units in the preview"
on = "K"
run = "seek -5"

[[manager.keymap]]
desc = "Seek down 5 units in the preview"
on = "J"
run = "seek 5"

[[manager.keymap]]
desc = "Toggle the current selection state"
on = "<Space>"
run = ["toggle --state=none", "arrow 1"]

[[manager.keymap]]
desc = "Enter visual mode (selection mode)"
on = "v"
run = "visual_mode"

[[manager.keymap]]
desc = "Enter visual mode (unset mode)"
on = "V"
run = "visual_mode --unset"

[[manager.keymap]]
desc = "Select all files"
on = "<C-a>"
run = "toggle_all --state=true"

[[manager.keymap]]
desc = "Inverse selection of all files"
on = "<C-r>"
run = "toggle_all --state=none"

[[manager.keymap]]
desc = "Open selected files"
on = "o"
run = "open"

[[manager.keymap]]
desc = "Open selected files interactively"
on = "O"
run = "open --interactive"

[[manager.keymap]]
desc = "Open selected files"
on = "<Enter>"
run = "open"

[[manager.keymap]]
desc = "Open selected files interactively"
on = "<S-Enter>"
run = "open --interactive"

[[manager.keymap]]
desc = "Yank selected files (copy)"
on = "y"
run = "yank"

[[manager.keymap]]
desc = "Yank selected files (cut)"
on = "x"
run = "yank --cut"

[[manager.keymap]]
desc = "Paste yanked files"
on = "p"
run = "paste"

[[manager.keymap]]
desc = "Paste yanked files (overwrite if the destination exists)"
on = "P"
run = "paste --force"

[[manager.keymap]]
desc = "Symlink the absolute path of yanked files"
on = "-"
run = "link"

[[manager.keymap]]
desc = "Symlink the relative path of yanked files"
on = "_"
run = "link --relative"

[[manager.keymap]]
desc = "Hardlink yanked files"
on = "<C-->"
run = "hardlink"

[[manager.keymap]]
desc = "Cancel the yank status"
on = "Y"
run = "unyank"

[[manager.keymap]]
desc = "Cancel the yank status"
on = "X"
run = "unyank"

[[manager.keymap]]
desc = "Trash selected files"
on = "d"
run = "remove"

[[manager.keymap]]
desc = "Permanently delete selected files"
on = "D"
run = "remove --permanently"

[[manager.keymap]]
desc = "Create a file (ends with / for directories)"
on = "a"
run = "create"

[[manager.keymap]]
desc = "Rename selected file(s)"
on = "r"
run = "rename --cursor=before_ext"

[[manager.keymap]]
desc = "Run a shell command"
on = ";"
run = "shell --interactive"

[[manager.keymap]]
desc = "Run a shell command (block until finishes)"
on = ":"
run = "shell --block --interactive"

[[manager.keymap]]
desc = "Toggle the visibility of hidden files"
on = "."
run = "hidden toggle"

[[manager.keymap]]
desc = "Search files by name using fd"
on = "s"
run = "search fd"

[[manager.keymap]]
desc = "Search files by content using ripgrep"
on = "S"
run = "search rg"

[[manager.keymap]]
desc = "Cancel the ongoing search"
on = "<C-s>"
run = "escape --search"

[[manager.keymap]]
desc = "Jump to a directory using zoxide"
on = "z"
run = "plugin zoxide"

[[manager.keymap]]
desc = "Jump to a directory or reveal a file using fzf"
on = "Z"
run = "plugin fzf"

[[manager.keymap]]
desc = "Set linemode to size"
on = ["m", "s"]
run = "linemode size"

[[manager.keymap]]
desc = "Set linemode to permissions"
on = ["m", "p"]
run = "linemode permissions"

[[manager.keymap]]
desc = "Set linemode to ctime"
on = ["m", "c"]
run = "linemode ctime"

[[manager.keymap]]
desc = "Set linemode to mtime"
on = ["m", "m"]
run = "linemode mtime"

[[manager.keymap]]
desc = "Set linemode to owner"
on = ["m", "o"]
run = "linemode owner"

[[manager.keymap]]
desc = "Set linemode to none"
on = ["m", "n"]
run = "linemode none"

[[manager.keymap]]
desc = "Copy the file path"
on = ["c", "c"]
run = "copy path"

[[manager.keymap]]
desc = "Copy the directory path"
on = ["c", "d"]
run = "copy dirname"

[[manager.keymap]]
desc = "Copy the filename"
on = ["c", "f"]
run = "copy filename"

[[manager.keymap]]
desc = "Copy the filename without extension"
on = ["c", "n"]
run = "copy name_without_ext"

[[manager.keymap]]
desc = "Filter files"
on = "f"
run = "filter --smart"

[[manager.keymap]]
desc = "Find next file"
on = "/"
run = "find --smart"

[[manager.keymap]]
desc = "Find previous file"
on = "?"
run = "find --previous --smart"

[[manager.keymap]]
desc = "Go to the next found"
on = "n"
run = "find_arrow"

[[manager.keymap]]
desc = "Go to the previous found"
on = "N"
run = "find_arrow --previous"

[[manager.keymap]]
desc = "Sort by modified time"
on = [",", "m"]
run = ["sort modified --reverse=no", "linemode mtime"]

[[manager.keymap]]
desc = "Sort by modified time (reverse)"
on = [",", "M"]
run = ["sort modified --reverse", "linemode mtime"]

[[manager.keymap]]
desc = "Sort by created time"
on = [",", "c"]
run = ["sort created --reverse=no", "linemode ctime"]

[[manager.keymap]]
desc = "Sort by created time (reverse)"
on = [",", "C"]
run = ["sort created --reverse", "linemode ctime"]

[[manager.keymap]]
desc = "Sort by extension"
on = [",", "e"]
run = "sort extension --reverse=no"

[[manager.keymap]]
desc = "Sort by extension (reverse)"
on = [",", "E"]
run = "sort extension --reverse"

[[manager.keymap]]
desc = "Sort alphabetically"
on = [",", "a"]
run = "sort alphabetical --reverse=no"

[[manager.keymap]]
desc = "Sort alphabetically (reverse)"
on = [",", "A"]
run = "sort alphabetical --reverse"

[[manager.keymap]]
desc = "Sort naturally"
on = [",", "n"]
run = "sort natural --reverse=no"

[[manager.keymap]]
desc = "Sort naturally (reverse)"
on = [",", "N"]
run = "sort natural --reverse"

[[manager.keymap]]
desc = "Sort by size"
on = [",", "s"]
run = ["sort size --reverse=no", "linemode size"]

[[manager.keymap]]
desc = "Sort by size (reverse)"
on = [",", "S"]
run = ["sort size --reverse", "linemode size"]

[[manager.keymap]]
desc = "Sort randomly"
on = [",", "r"]
run = "sort random --reverse=no"

[[manager.keymap]]
desc = "Go to the home directory"
on = ["g", "h"]
run = "cd ~"

[[manager.keymap]]
desc = "Go to the config directory"
on = ["g", "c"]
run = "cd ~/.config"

[[manager.keymap]]
desc = "Go to the downloads directory"
on = ["g", "d"]
run = "cd ~/Downloads"

[[manager.keymap]]
desc = "Go to a directory interactively"
on = ["g", "<Space>"]
run = "cd --interactive"

[[manager.keymap]]
desc = "Create a new tab with CWD"
on = "t"
run = "tab_create --current"

[[manager.keymap]]
desc = "Switch to the first tab"
on = "1"
run = "tab_switch 0"

[[manager.keymap]]
desc = "Switch to the second tab"
on = "2"
run = "tab_switch 1"

[[manager.keymap]]
desc = "Switch to the third tab"
on = "3"
run = "tab_switch 2"

[[manager.keymap]]
desc = "Switch to the fourth tab"
on = "4"
run = "tab_switch 3"

[[manager.keymap]]
desc = "Switch to the fifth tab"
on = "5"
run = "tab_switch 4"

[[manager.keymap]]
desc = "Switch to the sixth tab"
on = "6"
run = "tab_switch 5"

[[manager.keymap]]
desc = "Switch to the seventh tab"
on = "7"
run = "tab_switch 6"

[[manager.keymap]]
desc = "Switch to the eighth tab"
on = "8"
run = "tab_switch 7"

[[manager.keymap]]
desc = "Switch to the ninth tab"
on = "9"
run = "tab_switch 8"

[[manager.keymap]]
desc = "Switch to the previous tab"
on = "["
run = "tab_switch -1 --relative"

[[manager.keymap]]
desc = "Switch to the next tab"
on = "]"
run = "tab_switch 1 --relative"

[[manager.keymap]]
desc = "Swap current tab with previous tab"
on = "{"
run = "tab_swap -1"

[[manager.keymap]]
desc = "Swap current tab with next tab"
on = "}"
run = "tab_swap 1"

[[manager.keymap]]
desc = "Show task manager"
on = "w"
run = "tasks_show"

[[manager.keymap]]
desc = "Open help"
on = "~"
run = "help"

[[manager.keymap]]
desc = "Open help"
on = "<F1>"
run = "help"

[[manager.prepend_keymap]]
desc = "Open shell here"
on = "!"
run = "shell \"$SHELL\" --block --confirm"

[[manager.prepend_keymap]]
desc = "Enter the child directory, or open the file"
on = ["l"]
run = "plugin smart-enter"

[[manager.prepend_keymap]]
desc = "Paste into the hovered directory or CWD"
on = ["p"]
run = "plugin smart-paste"

[[manager.prepend_keymap]]
desc = "Copy the selected files to the system clipboard while yanking"
on = ["y"]
run = ["shell 'for path in \"$@\"; do echo \"file://$path\"; done | wl-copy -t text/uri-list' --confirm\n", "yank"]

[[manager.prepend_keymap]]
desc = "Drag and drop via ripdrag"
on = ["<C-n>"]
run = ["shell 'ripdrag \"$@\" -x 2>/dev/null &' --confirm\n", "echo \"Control + N Pressed\"\n"]

[[manager.prepend_keymap]]
desc = "Maximize or restore preview pane"
on = ["T"]
run = "plugin max-preview"

[[manager.prepend_keymap]]
desc = "Move the cursor down"
on = ["k"]
run = "plugin arrow --args=-1"

[[manager.prepend_keymap]]
desc = "Move the cursor up"
on = ["j"]
run = "plugin arrow --args=1"

[[manager.prepend_keymap]]
desc = "Go to the root of the current Git repository"
on = ["g", "r"]
run = "shell 'ya emit cd \"$(git rev-parse --show-toplevel)\"' --confirm\n"

[[manager.prepend_keymap]]
desc = "run lazygit"
on = ["g", "i"]
run = "plugin lazygit"

[[manager.prepend_keymap]]
desc = "Toggle tree/list dir preview"
on = ["E"]
run = "plugin eza-preview"

[[manager.prepend_keymap]]
desc = "Chmod the selected files"
on = ["c,m"]
run = "plugin chmod"

[[manager.prepend_keymap]]
desc = "Compress with ouch"
on = ["C"]
run = "plugin ouch --args=zip"

[[select.keymap]]
desc = "Cancel selection"
on = "<Esc>"
run = "close"

[[select.keymap]]
desc = "Cancel selection"
on = "<C-[>"
run = "close"

[[select.keymap]]
desc = "Cancel selection"
on = "<C-c>"
run = "close"

[[select.keymap]]
desc = "Submit the selection"
on = "<Enter>"
run = "close --submit"

[[select.keymap]]
desc = "Move cursor up"
on = "k"
run = "arrow -1"

[[select.keymap]]
desc = "Move cursor down"
on = "j"
run = "arrow 1"

[[select.keymap]]
desc = "Move cursor up"
on = "<Up>"
run = "arrow -1"

[[select.keymap]]
desc = "Move cursor down"
on = "<Down>"
run = "arrow 1"

[[select.keymap]]
desc = "Open help"
on = "~"
run = "help"

[[select.keymap]]
desc = "Open help"
on = "<F1>"
run = "help"

[[tasks.keymap]]
desc = "Close task manager"
on = "<Esc>"
run = "close"

[[tasks.keymap]]
desc = "Close task manager"
on = "<C-[>"
run = "close"

[[tasks.keymap]]
desc = "Close task manager"
on = "<C-c>"
run = "close"

[[tasks.keymap]]
desc = "Close task manager"
on = "w"
run = "close"

[[tasks.keymap]]
desc = "Move cursor up"
on = "k"
run = "arrow -1"

[[tasks.keymap]]
desc = "Move cursor down"
on = "j"
run = "arrow 1"

[[tasks.keymap]]
desc = "Move cursor up"
on = "<Up>"
run = "arrow -1"

[[tasks.keymap]]
desc = "Move cursor down"
on = "<Down>"
run = "arrow 1"

[[tasks.keymap]]
desc = "Inspect the task"
on = "<Enter>"
run = "inspect"

[[tasks.keymap]]
desc = "Cancel the task"
on = "x"
run = "cancel"

[[tasks.keymap]]
desc = "Open help"
on = "~"
run = "help"

[[tasks.keymap]]
desc = "Open help"
on = "<F1>"
run = "help"
