# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#ca9ee6" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e5c890", bold = true, italic = true, underline = true }
find_position = { fg = "#eebebe", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#a6d189", bg = "#a6d189" }
marker_cut      = { fg = "#e78284", bg = "#e78284" }
marker_marked   = { fg = "#81c8be", bg = "#81c8be" }
marker_selected = { fg = "#e5c890", bg = "#e5c890" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#303446", bg = "#a6d189" }
count_cut      = { fg = "#303446", bg = "#e78284" }
count_selected = { fg = "#303446", bg = "#e5c890" }

# Border
border_symbol = "│"
border_style  = { fg = "#ca9ee6" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#303446", bg = "#ca9ee6", bold = true }
normal_alt  = { fg = "#ca9ee6", bg = "#303446" }

# Select mode
select_main = { fg = "#303446", bg = "#babbf1", bold = true }
select_alt  = { fg = "#babbf1", bg = "#303446" }

# Unset mode
unset_main = { fg = "#303446", bg = "#eebebe", bold = true }
unset_alt  = { fg = "#eebebe", bg = "#303446" }

# : }}}


# : Status bar {{{

[status]
separator_open  = ""
separator_close = ""

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#303446", bg = "#babbf1" }
progress_error  = { fg = "#e78284", bg = "#babbf1" }

# Permissions
perm_sep   = { fg = "#babbf1" }
perm_type  = { fg = "#babbf1" }
perm_read  = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec  = { fg = "#a6d189" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#babbf1" }
active   = { fg = "#eebebe", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#babbf1" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#babbf1" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#babbf1" }
title   = {}
hovered = { fg = "#eebebe", underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#303446" }
cand            = { fg = "#ca9ee6" }
rest            = { fg = "#babbf1" }
desc            = { fg = "#eebebe" }
separator       = "  "
separator_style = { fg = "#303446" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#ca9ee6" }
run     = { fg = "#eebebe" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#303446", bg = "#c6d0f5" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#a6d189" }
title_warn  = { fg = "#e5c890" }
title_error = { fg = "#e78284" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#ca9ee6" },

  # Media
  { mime = "{audio,video}/*", fg = "#e5c890" },

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#eebebe" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#a6d189" },

  # Fallback
  { name = "*", fg = "#c6d0f5" },
  { name = "*/", fg = "#babbf1" }
]

# : }}}
